
description: GRU based model included
data_dir: /bigpool/projects/yao_SCANGAN360/New_Folder/tf_records_w_cm_fv_diff_unequal
log_dir: /netpool/work/gpu-3/users/malyalasa/New_folder/rosbag2numpy/logging

H_BATCH_SIZE : 16
H_SHUFFLE_BUFFER : 4000
normalize_coords: True
normalize_factor: 1536.0
epochs: 60
lr: 0.01 #0.025
optimizer: nadam
metric: mse
losses: mae

#model params
model_name: GRUmodel
  #BidiLSTM
  #hybridmodel 
#TimeDistributedDense
layer1_Dense_units: 4
layer1_LSTM_units: 2
layer1_GRU_units: 2

#model_type: TimeDistributedDense
