
description: feature vector model with config yaml
data_dir: /bigpool/projects/yao_SCANGAN360/New_Folder/tf_records_w_cm_fv_diff_unequal
log_dir: /netpool/work/gpu-3/users/malyalasa/New_folder/rosbag2numpy/logging

H_BATCH_SIZE : 8
H_SHUFFLE_BUFFER : 3200
normalize_coords: True
normalize_factor: 1536.0
epochs: 90
lr: 0.02
optimizer: rmsprop
metric: mse
losses: mae

#model params
layer_1_units: 4

#model_type: TimeDistributedDense
